name: FineCar Inventory CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    #  postgress service  run
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        # Define health checks to ensure the data base is redy before running  tests

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Run our custom composite action
      - name: Run Environment Setup Action
        id: setup
        uses: ./.github/actions/setup-env

      # Search test database ready before running tests
      - name: Run Tests with Pytest
        env:
          DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db
        run: |
          python -m pytest

      - name: List files
        shell: bash
        run: ls -R

      # Custom Action out out status prints
      - name: Print Custom Action Output Status
        run: echo "Dependency setup status was ${{ steps.setup.outputs.status }}"
